name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout sources"
      uses: actions/checkout@v3

    - name: "Setup Java"
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '19'
        cache: 'gradle'

    - name: "Run Gradle build"
      run: chmod 755 gradlew && ./gradlew build --no-daemon

    - name: "Zip build reports"
      if: failure()
      run: zip -r reports.zip build/reports

    - uses: actions/upload-artifact@v3
      name: "Upload build reports"
      if: failure()
      with:
        name: reports
        path: reports.zip
